"API": "30 - API"
"BENCH": "28 - Benchmark"
"BUG": "00 - Bug"
"DEP": "07 - Deprecation"
"DEV": "16 - Development"
"DOC": "04 - Documentation"
"ENH": "01 - Enhancement"
"MAINT": "03 - Maintenance"
"REV": "34 - Reversion"
"TST": "05 - Testing"
"REL": "14 - Release"
"WIP": "25 - WIP"
