image: thomasjpfan/numpy-gitpod:latest
tasks:
  # The base image complied numpy with ccache enabled. This second build
  # should be faster since it is using the cache.
  - init: python setup.py build_ext -i

github:
  prebuilds:
    master: true
    branches: true
