name: Build_Test

on: [push, pull_request]

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: BeforeInstall
      run: ./tools/travis-before-install.sh

    - name: Test
      run: ./tools/travis-test.sh
 
  build_test:
    needs: smoke_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        exclude:
          # This ran in the smoke_test
          - python-version: 3.8
        include:
          - env:
              USE_DEBUG: 1
            python-version: 3.8
          - env: 
              NPY_USE_BLAS_ILP64: 1
            python-version: 3.8
          - env:
              USE_WHEEL: 1
              RUN_FULL_TESTS: 1
              RUN_COVERAGE: 1
              INSTALL_PICKLE5: 1
            python-version: 3.7
          - env:
              PYTHONOPTIMIZE: 2
              BLAS: None
              LAPACK: None
              ATLAS: None
              NPY_BLAS_ORDER: mkl,blis,openblas,atlas,blas
              NPY_LAPACK_ORDER: MKL,OPENBLAS,ATLAS,LAPACK
              USE_ASV: 1
            python-version: 3.7
          - env:
              NPY_RELAXED_STRIDES_CHECKING: 0
              DOWNLOAD_OPENBLAS: 1
              CHECK_BLAS: 1
              NPY_USE_BLAS_ILP64: 1
            python-version: 3.7
          - env:
              USE_WHEEL: 1
              NPY_RELAXED_STRIDES_DEBUG: 1
            python-version: 3.7
          - env:
              NUMPY_EXPERIMENTAL_ARRAY_FUNCTION: 0
            python-version: 3.7
          - env:
              BLAS: None
              LAPACK: None
              ATLAS: None
            python-version: 3.7

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: BeforeInstall
      run: ./tools/travis-before-install.sh

    - name: Test
      run: ./tools/travis-test.sh
        
