name: Test on Cygwin
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cygwin_build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: 'C:\tools\cygwin'
          packages: >
            python37-devel python37-zipp python37-importlib-metadata
            python37-cython python37-pip python37-wheel python37-cffi
            python37-pytz python37-setuptools python37-pytest
            python37-hypothesis liblapack-devel libopenblas
            gcc-fortran git dash
      - name: Set Windows PATH
        uses: egor-tensin/cleanup-path@v1
        with:
          dirs: 'C:\tools\cygwin\bin;C:\tools\cygwin\lib\lapack'
      - name: Verify that bash is Cygwin bash
        run: |
          command bash
          bash -c "uname -svrmo"
      - name: Update with Cygwin git
        # fetch-depth=0 above should make this short.
        run: |
          dash -c "which git; /usr/bin/git fetch --all -p"
      - name: Verify python version
        # Make sure it's the Cygwin one, not a Windows one
        run: |
          dash -c "which python3.7; /usr/bin/python3.7 --version -V"
      - name: Build NumPy wheel
        run: |
          dash -c "/usr/bin/python3.7 -m pip install 'setuptools<49.2.0' pytest pytz cffi pickle5 importlib_metadata typing_extensions"
          dash -c "/usr/bin/python3.7 -m pip install -r test_requirements.txt"
          dash -c "/usr/bin/python3.7 setup.py bdist_wheel"
      - name: Install new NumPy
        run: |
          bash -c "/usr/bin/python3.7 -m pip install dist/numpy-*cp37*.whl"
      - name: Run NumPy test suite
        run: >-
          dash -c "/usr/bin/python3.7 runtests.py -n -vv"
      - name: Upload wheel if tests fail
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: numpy-cygwin-wheel
          path: dist/numpy-*cp37*.whl
      - name: On failure check the extension modules
        if: failure()
        run: |
          dash -c "/usr/bin/python3.7 -m pip show numpy"
          dash -c "/usr/bin/python3.7 -m pip show -f numpy | grep .dll"
          dash -c "/bin/tr -d '\r' <tools/list_installed_dll_dependencies_cygwin.sh >list_dlls_unix.sh"
          dash "list_dlls_unix.sh"
